name: api_client
description: A client for the Orb API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  api_models:
    path: ../api_models
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.1.2
  http_parser: ^4.0.2
  native_dio_adapter: ^1.3.0
  platform: ^3.1.4
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
