name: doctor
description: Doctor Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  convert: ^3.1.1
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.9
  lottie: ^2.1.0
  pedantic: ^1.11.1
  provider: ^6.0.3
  logger: ^1.1.0
  flutter_screenutil: ^5.9.0 # for responsive dimensions
  fluttertoast: ^8.0.9 # for showing toast
  flutter_bloc: ^8.1.1 # Flutter Bloc for Event & State management
  kiwi: ^4.0.2 # For Dependency Injection
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.5
  share_plus: ^6.3.0
  social_share: ^2.2.1
  material_design_icons_flutter: ^6.0.7096
  font_awesome_flutter: ^10.2.1
  path_provider: ^2.0.11 # for getting storage path
  permission_handler: ^11.0.1 # for handling permission
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.2
  flutter_brand_palettes: ^0.5.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  file_picker: ^5.2.7
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  uni_links: ^0.5.1
  retry: ^3.1.0
  drift: ^2.13.0
  flutter_hooks: ^0.18.5+1
  flutter_secure_storage: ^5.0.2
  #  sqlcipher_flutter_libs: ^0.5.1
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.17
  quiver: ^3.2.1
  flutter_local_notifications: ^16.1.0
  diffutil_dart: ^3.0.0
  equatable: ^2.0.5
  flutter_chat_types: ^3.6.1
  flutter_link_previewer: ^3.2.1
  flutter_parsed_text: ^2.2.1
  meta: ^1.9.1
  photo_view: ^0.14.0
  scroll_to_index: ^3.0.1
  visibility_detector: ^0.4.0+2
  #maps_launcher: ^2.2.0
  linkify: ^5.0.0
  bloc: ^8.1.2
  html: ^0.15.4
  string_validator: ^0.3.0
  async: ^2.11.0
  path: ^1.8.3
  grpc: ^3.2.4
  http_parser: ^4.0.2
  flutter_animate: ^4.2.0+1
  collection: ^1.17.2
  bloc_concurrency: ^0.2.2
  fwfh_text_style: ^2.23.8
  flutter_webrtc: ^0.9.41
  flutter_riverpod: ^2.4.0
  huddle01_auth: ^0.0.2
  flutter_datetime_picker_plus: ^2.1.0
  flutter_app_badger: ^1.5.0

  platform: ^3.1.3
  huddle01_flutter_client: ^0.0.1-beta-v5.2.5
dependency_overrides:
  intl: ^0.18.1
  visibility_detector: ^0.4.0+2
  http: ^0.13.6
  protobuf: 3.0.0
  wakelock: ^0.6.2
  win32: 4.0.0
  flutter_webrtc: ^0.9.41
  logger: ^2.0.2
  dart_webrtc: 1.1.3
  webrtc_interface: 1.1.0
  shimmer: ^3.0.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.9
  kiwi_generator: ^4.0.2
  json_serializable: ^6.7.1
  drift_dev: ^2.12.1
  web3dart_builders: ^0.0.2
  dart_code_metrics: ^5.7.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          style: italic
          weight: 100
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Variable.ttf
    - family: TwitterSpace
      fonts:
        - asset: assets/fonts/TwitterSpace.ttf
