name: orb_mobile
description: Orb mobile app
version: 1.227.1
publish_to: none
environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: 3.19.4
dependencies:
  animations: ^2.0.11
  api_client:
    path: packages/api_client
  api_models:
    path: packages/api_models
  app_ui:
    path: packages/app_ui
  user_repository:
    path: packages/user_repository
  secure_storage:
    path: packages/storage/secure_storage
  appcheck: ^1.1.0
  async: ^2.11.0
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  # Pointing to forked repo to fix the issue with the following issue:
  # * https://github.com/Apparence-io/CamerAwesome/issues/450
  # * https://orb-app.sentry.io/issues/4975737593/events/f2ce52302bf244c3ba98201900b00b18/
  carousel_slider: ^4.2.1
  clock: ^1.1.1
  collection: ^1.18.0
  draggable_scrollbar: ^0.1.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  extended_image: ^8.2.0
  fake_async: ^1.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.20
  flutter_media_metadata: ^1.0.0+1
  flutter_secure_storage: ^9.0.0
  persistent_storage:
    path: packages/storage/persistent_storage
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.9
  # Pointing to a fork of flutter_swipe_detector to fix the following issue:
  # LateInitializationError: Field '_updatePosition@1376331832' has not been initialized.
  # * https://orb-app.sentry.io/issues/4820439951/events/8578f0d6f8fc4431a762f7ce3125c3e4/
  flutter_swipe_detector:
    git:
      url: https://github.com/korzonkiee/flutter_swipe_detector.git
      ref: fix/updatePosition-has-not-been-initialised
  flutter_video_info: ^1.3.1
  giphy_get: ^3.5.4
  go_router: ^13.2.0
  intl: any
  keyboard_height_plugin: ^0.0.5
  linkify: ^5.0.0
  local_hero: ^0.3.0
  logging: ^1.2.0
  lottie: ^3.1.2
  marquee: ^2.2.3
  mime: ^1.0.5
  path_provider: ^2.1.2
  pin_code_fields:
    git:
      url: https://github.com/orb-club/pin_code_fields.git
      ref: feat/show-paste-dialog-flag
  platform: ^3.1.3
  provider: ^6.1.1
  retry: ^3.1.2
  rxdart: ^0.27.7
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12
  social_share: ^2.3.1
  step_progress_indicator: ^1.0.2
  timeago: ^3.6.1
  timeago_flutter: ^3.6.0
  video_player: ^2.8.2
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0+2
dev_dependencies:
  flutter_gen_runner: ^5.4.0
dependency_overrides:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  build_version: ^2.1.1
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.3
  mocktail_image_network: ^1.1.0
  very_good_analysis: ^5.1.0
flutter:
  uses-material-design: true
  generate: true