name: app_ui
description: Application UI library for Orb.
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  animations: ^2.0.8
  # TODO(ManmohanTalwar): to remove [assorted_layout_widgets] dependency.
  assorted_layout_widgets: ^9.0.0
  cached_network_image: ^3.3.0
  dotted_line: ^3.2.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  intl: ^0.18.1
  local_hero: ^0.3.0
  lottie: ^3.1.2
  rich_text_view:
    git:
      # A fork of `RichTextView` with the following fixes:
      # - https://github.com/orb-club/rich_text_view/pull/1
      # - https://github.com/orb-club/rich_text_view/pull/2
      # - https://github.com/orb-club/rich_text_view/pull/3
      # - https://github.com/orb-club/rich_text_view/pull/4
      url: https://github.com/orb-club/rich_text_view.git

  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
    - assets/lottie/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Bold-Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Semibold-Italic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Medium-Italic.otf
          weight: 500
          style: italic
    - family: SSProRegularDisplay
      fonts:
        - asset: assets/fonts/source-sans-pro-regular.ttf
          weight: 700
flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
  fonts: 
    enabled: false
  output: lib/src/generated/
  lineLength: 80

  integrations:
    flutter_svg: true
